name: myenv
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.9
  - numpy
  - scipy
  - pandas
  - matplotlib
  - sympy
  - jupyter
  - notebook
  - ipython
  - ipykernel
  - pytorch
  - torchvision
  - torchaudio
  - pip
  - pip:
      - absl-py==2.0.0
      - anyio==4.0.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - astunparse==1.6.3
      - async-lru==2.0.4
      - attrs==23.1.0
      - backpack-for-pytorch==1.6.0
      - beautifulsoup4==4.12.2
      - bleach==6.1.0
      - cachecontrol==0.14.0
      - cachetools==5.3.1
      - certifi==2023.7.22
      - cffi==1.16.0
      - charset-normalizer==3.3.0
      - click==8.1.7
      - colorama==0.4.6
      - contourpy==1.1.1
      - cryptography==42.0.8
      - cycler==0.12.1
      - docker-pycreds==0.4.0
      - einops==0.8.0
      - fastjsonschema==2.18.1
      - fonttools==4.43.1
      - fsspec==2024.3.1
      - google-auth==2.23.3
      - google-auth-oauthlib==1.0.0
      - grpcio==1.59.0
      - h5py==3.10.0
      - jupyterlab==4.0.7
      - keras==2.14.0
      - matplotlib==3.8.0
      - notebook==7.0.6
      - numba==0.60.0
      - opt-einsum==3.3.0
      - pandas==2.1.1
      - pillow==10.3.0
      - plotly==5.17.0
      - protobuf==4.24.4
      - pyparsing==3.1.1
      - pyro-ppl==1.9.0
      - requests==2.31.0
      - scikit-learn==1.3.0
      - seaborn==0.13.0
      - tensorboard==2.14.1
      - tensorflow==2.14.0
      - torch==2.2.2
      - torchvision==0.17.2
      - torchaudio==2.2.2
      - tqdm==4.66.1
      - umap-learn==0.5.6
      - wandb==0.17.4
      - werkzeug==3.0.0
prefix: /home/shireen/miniconda3/envs/myenv
